kak: better grep no matter where it's been trigger
Signed-off-by: Tw <tw19881113@gmail.com>
Change-Id: I870c865771f4b3b493e740f780e4d8496a6a6964

diff --git a/.config/kak/kakrc b/.config/kak/kakrc
--- a/.config/kak/kakrc
+++ b/.config/kak/kakrc
@@ -49,4 +49,26 @@ cursorline
 # fzf for files and searches
 pathogen-infect "%val{config}/fzf"
 
-map global user g "<a-i>w:git grep <c-r>.<ret>" -docstring 'git grep search'
+define-command -hidden grep_from_top %{
+	execute-keys %sh{
+		topdir() {
+	        dirname_buffer="${kak_buffile%/*}"
+	        if [ "${dirname_buffer}" = "${kak_buffile}" ]; then
+	            printf 'fail grep_from_top: cannot operate on scratch buffer: %s\n' "${kak_buffile}"
+	            return 1
+	        fi
+	        cd "${dirname_buffer}" 2>/dev/null || {
+	            printf 'fail grep_from_top: unable to change the current working directory to: %s\n' "${dirname_buffer}"
+	            return 1
+	        }
+	        git_topdir="$(git rev-parse --show-toplevel)"
+	        if [ "${git_topdir}" != "${HOME}" ]; then
+	        	printf "%s" "$(realpath ${git_topdir})"
+        	else
+	        	printf "%s" "$(realpath ${dirname_buffer})"
+	        fi
+	    }
+		printf ":grep -I -w %s %s<ret>" "${kak_selection}" "$(topdir)"
+	}
+}
+map global user g "<a-i>w:grep_from_top<ret>" -docstring 'grep word at current cursor'
